[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[project]
name            = "thermur"
version         = "0.2.0"
description     = "Thermally-constrained flocking and color-mapping for wildfires."
authors         = [{ name = "James Parkington", email = "pongs.acreage.0o@icloud.com" }]
readme          = "README.md"
requires-python = ">=3.13"
license         = { text = "MIT" }
dependencies    = [
    "hydra-zen",
    "lightning",
    "netcdf4",
    "pydantic",
    "pydantic-settings",
    "pyarrow",
    "questionary",
    "rich",
    "scipy",
    "torch",
    "torch-geometric",
    "torchmetrics",
    "typer",
    "wandb[media]",
    "xarray"
]

[project.scripts]
thermur = "thermur.cli.cli:main"

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/config", "src/thermur"]
